https://blog.csdn.net/kalath_aiur/article/details/105234675

对于分类问题，常见的弱学习器包括：

决策树：通常是深度较浅的决策树，例如单层决策树（stump）或有限深度的决策树。
朴素贝叶斯分类器：如高斯朴素贝叶斯、多项式朴素贝叶斯等。
支持向量机（SVM）：可以使用线性核或非线性核函数。
k近邻分类器：基于样本之间的距离进行分类。
逻辑回归：用于二分类问题。
对于回归问题，常见的弱学习器包括：

决策树回归器：如单层决策树回归器。
线性回归：用于拟合线性关系。
支持向量回归（SVR）：可以使用线性核或非线性核函数。

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
import numpy as np

X = np.arange(10).reshape(-1,1)
y = np.array([1,1,1,-1,-1,-1,1,1,1,-1])


In [7]:
from sklearn.ensemble import AdaBoostClassifier
import numpy as np

X = np.arange(10).reshape(-1,1)
y = np.array([1,1,1,-1,-1,-1,1,1,1,-1])

# w1为初始权重，所有样本的初始权重相等
w1 = np.full(shape = 10,fill_value=0.1)
print(w1.shape,X.shape)

# 循环计算误差率，取最小值。
thresholds = np.arange(0.5,10)

for i, t in enumerate(thresholds, start = 1): 
   # print(i,t)
	# y_是弱分类器的预测值
    y_ = np.array([1]*i + [-1]*(10-i))
    print(t,((y !=y_)*w1).sum())

e1 = 0.3
a1 = 1/2*np.log((1 -e1)/e1 )
print('第一个弱分类器的权重为:',a1)

# y_为第一个弱分类器的预测结果
y_ = np.array([1]*3 + [-1]*(10-3))
# w2为更新后的样本权重
w2 = w1*np.exp(-y*y_*a1)
w2 = w2/w2.sum()

print(w2)
print(y_)
print(y)

(10,) (10, 1)
0.5 0.5
1.5 0.4
2.5 0.30000000000000004
3.5 0.4
4.5 0.5
5.5 0.6
6.5 0.5
7.5 0.4
8.5 0.30000000000000004
9.5 0.4
第一个弱分类器的权重为: 0.42364893019360184
[0.07142857 0.07142857 0.07142857 0.07142857 0.07142857 0.07142857
 0.16666667 0.16666667 0.16666667 0.07142857]
[ 1  1  1 -1 -1 -1 -1 -1 -1 -1]
[ 1  1  1 -1 -1 -1  1  1  1 -1]


In [9]:
#第二个弱分类器
thresholds = np.arange(0.5,10)
for i,t in enumerate(thresholds, start = 1):
    y_ = np.array([1]*i + [-1]*(10-i))
    print(t,((y != y_)*w2).sum())
#阈值为8.5时，误差最小
y_ = np.array([1]*9 + [-1]*(10-9))
e2 = ((y != y_)*w2).sum()
a2 = 1/2*np.log((1 - e2)/e2)
print('第二个弱分类器的权重是：',a2)

y_ = np.array([1]*9 + [-1]*(10-9))
w3 = w2*np.exp(-y*y_*a2)
w3 = w3/w3.sum()

print(w3)
print(y_)
print(y)

0.5 0.6428571428571428
1.5 0.5714285714285714
2.5 0.5
3.5 0.5714285714285714
4.5 0.6428571428571428
5.5 0.7142857142857142
6.5 0.5476190476190476
7.5 0.38095238095238093
8.5 0.21428571428571425
9.5 0.28571428571428564
第二个弱分类器的权重是： 0.6496414920651306
[0.04545455 0.04545455 0.04545455 0.16666667 0.16666667 0.16666667
 0.10606061 0.10606061 0.10606061 0.04545455]
[ 1  1  1  1  1  1  1  1  1 -1]
[ 1  1  1 -1 -1 -1  1  1  1 -1]


In [11]:
#第3个分类器
thresholds = np.arange(0.5,10)
for i,t in enumerate(thresholds,start = 1): 
    y_ = np.array([1]*i + [-1]*(10-i))
    print(t,((y !=y_)*w3).sum())

e3 = 0.1820
# 计算第三个弱分类器的权重。
y_ = np.array([-1]*6 + [1]*(10-6))
a3 = 1/2*np.log((1 - e3)/e3)
print('第三个弱分类器的权重是：',a3)
# 更新样本权重
w4 = w3*np.exp(-y*y_*a3)
w4 = w4/w4.sum()

print(w4)
print(y_)
print(y)

0.5 0.4090909090909091
1.5 0.36363636363636365
2.5 0.3181818181818182
3.5 0.48484848484848486
4.5 0.6515151515151515
5.5 0.8181818181818181
6.5 0.7121212121212122
7.5 0.6060606060606061
8.5 0.5
9.5 0.5454545454545454
第三个弱分类器的权重是： 0.7514278247629759
[0.12492364 0.12492364 0.12492364 0.10191407 0.10191407 0.10191407
 0.06485441 0.06485441 0.06485441 0.12492364]
[-1 -1 -1 -1 -1 -1  1  1  1  1]
[ 1  1  1 -1 -1 -1  1  1  1 -1]


In [13]:
# 第一个弱分类器的预测结果
y1 = np.array([1]*3 + [-1]*(10-3))
# 第二个弱分类器的预测结果
y2 = np.array([1]*9 + [-1]*(10-9))
# 第三个弱分类器的预测结果
y3 = np.array([-1]*6 + [1]*(10-6))
F =  a1*y1 + a2*y2 + a3*y3

print(F)
result = [-1 if i < 0 else 1 for i in F]
print(result)
print(y)

[ 0.3218626   0.3218626   0.3218626  -0.52543526 -0.52543526 -0.52543526
  0.97742039  0.97742039  0.97742039 -0.3218626 ]
[1, 1, 1, -1, -1, -1, 1, 1, 1, -1]
[ 1  1  1 -1 -1 -1  1  1  1 -1]


In [14]:
# 构建模型
ada = AdaBoostClassifier(algorithm='SAMME',n_estimators=3)
# 训练模型
ada.fit(X,y)
# 模型预测
ada.predict(X)


array([ 1,  1,  1, -1, -1, -1,  1,  1,  1, -1])

# 多分类

In [3]:
import numpy as np
np.exp(-0.65)*0.07

0.036543204373271125